### ISSUE TITLE
Перестает работать аннотация @Step при добавлении библиотеки с кастомными аспектами

### ISSUE THREAD

**Issue by MuTalKing** [kochetkov-ma/kotest-allure#2]
Максим, добрый день! Использую вашу библиотеку в своем проекте. Все было замечательно, аннотация @Step работала и в отчете можно было это увидеть:
![image](https://user-images.githubusercontent.com/57095429/135885018-61227ade-61af-4fb2-ae60-8490e3388bc5.png)

Пример использования @Step, который виден в отчете:
```
@Step("Open uat url Cabinet")
    fun getUrlUat(url: String = this.url) {
        driver.get(url)
    }
```
    
Мой build.gradle.kts выглядит так:
```
import org.gradle.internal.os.OperatingSystem.current
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.kotlin.konan.file.File
import org.jetbrains.kotlin.konan.properties.Properties
import org.jetbrains.kotlin.konan.properties.saveToFile
import java.io.FileInputStream

plugins {
    java
    kotlin("jvm") version "1.5.21"
    id("io.qameta.allure") version "2.8.1"
}

group = "ru.gogolev"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven("https://maven.repository.redhat.com/ga/")
    maven("https://repository.jboss.org/nexus/content/repositories/public/")
}

allure {
    autoconfigure = true
    version = "2.15.0"
    clean = true
    aspectjweaver = true
    aspectjVersion = "1.9.7"
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("log4j", "log4j", "1.2.+")
    implementation("org.seleniumhq.selenium", "selenium-java", "3.+")
    implementation("io.github.bonigarcia", "webdrivermanager", "4.+")
    implementation("com.oracle.ojdbc", "ojdbc8", "19.3.0.+")
    implementation("io.kotest:kotest-framework-api-jvm:4.5.+")
    implementation("io.kotest:kotest-runner-junit5-jvm:4.5.+")
    implementation("io.kotest:kotest-runner-console-jvm:4.1.+")
    implementation("ru.iopump.kotest:kotest-allure:1.0.1")
    implementation("io.qameta.allure:allure-kotlin-commons:2.2.6")
    implementation("io.qameta.allure:allure-java-commons:2.15.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.+")
    runtimeOnly("org.aspectj:aspectjweaver:1.9.7")
    implementation("com.rabbitmq:amqp-client:5.13.+")
    implementation("com.avmc:stallion:1.3.+")
    implementation("org.json:json:20171018")
    implementation("org.javassist:javassist:3.28.0-GA")
    implementation("dependencies:client:16.1.0.72-SNAPSHOT")

    implementation("org.slf4j:slf4j-simple:1.7.31")
    implementation("javax.jms:javax.jms-api:2.0.1")
    testImplementation("io.rest-assured:rest-assured:4.4.0")
    implementation("org.jooq:jooq:3.15.3")
    implementation("com.microsoft.sqlserver:mssql-jdbc:9.4.0.jre11")

}

tasks.test {
    minHeapSize = "1024m"
    maxHeapSize = "2048m"
    useJUnitPlatform()
    systemProperty("allure.results.directory", "$projectDir/build/allure-results")
    doFirst {
        systemProperties["kotest.framework.parallelism"] = 1
        }
    doLast {
        copy {
            from("src/test/resources/environment.properties")
            into(allure.resultsDir)
        }
        val props = Properties()
        val dirProperties = "${allure.resultsDir}/environment.properties"
        props.load(FileInputStream(dirProperties))
        props["OS.version"] = current().toString()
        props["kotlin.version"] = kotlin.coreLibrariesVersion
        props["GRADLE.version"] = gradle.gradleVersion
        props["allure.version"] = allure.version
        props["aspectjVersion.version"] = allure.aspectjVersion
        props["java.version"] = JavaVersion.current().toString()
        props.saveToFile(File(dirProperties))
    }

}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "11"
}
```

К сожалению, добавив библиотеку, в которой есть кастомные аспекты, аннотация @Step перестала работать:
![image](https://user-images.githubusercontent.com/57095429/135886298-f8226289-440c-40bf-8b3a-06816cdb7dd5.png)

Теперь отчет выглядит так:
![image](https://user-images.githubusercontent.com/57095429/135887386-ef2bcc9b-cd41-400e-9366-b4ef9ba8ae57.png)

При этом в логах видно, что он подгружает все аспекты - в том числе аллюровские:
![image](https://user-images.githubusercontent.com/57095429/135887306-db58ff75-e2f9-4287-b0be-77d5f9509b8f.png)

Библиотека с катомными аспектами использует также aspectjweaver. Я эксклюдил все библиотеки, которые она подтягивает - не помогло.
Я пытался использовать последнюю версию аллюровского плагина. Я использовал io.freefair.aspectj.base плагин, разные версии aspectjweaver - ничего не помогло.

Я излазил все темы про неработущую аннотацию @step, но похожую проблему ни у кого не нашел. Там в основном все решения сводились к подключению aspectjweaver
 
Подскажите, пожалуйста, с чем может быть связано и куда копать?

**Comment by kochetkov-ma** [comment]
Не думал что, кто то кроме меня пользуется этим расширением. Кажется, что аспекты конфликтуют. Я попробую воспроизвести у себя.
Нет ли в aspectj уровня логирования, где он пишет все точки где применился аспект или возможность посмотреть сгенерированный байткод?
Можно через настройку попробовать отключать по одному кастомные аспекты и найти тот на котором все лоамется, но судя по их кол-ву руками это довольно долго

**Comment by MuTalKing** [comment]
Максим, спасибо, что откликнулись. Ваш фреймворк работает лучше, чем kotest-extensions-allure. Почему то при использовании спецификации FreeSpec, kotest-extensions-allure считает каждый шаг отдельным кейсом и не формирует container.json (либо я его неправильно настраиваю). А ваш фреймворк формирует. И получается красивый отчет.

По поводу ошибки - отключил все кастомные аспекты, но @Step все равно не работает. То есть проблема не в конфликте аспектов.

Оказывается дело в секции weaver. Если без подтягивания всяких сторонних библиотек создать файл aop.xml и прописать в нем секцию weaver, то аллюровские аннотации перестают работать:
![image](https://user-images.githubusercontent.com/57095429/144246454-8b557f40-1b96-419f-8e43-4dd3e1e4147b.png)

Если оставить только секцию aspects, то все будет работать.

В моем случае оказалось, что нужная мне библиотека с кастомными аспектами содержит aop.xml, где как раз прописана секция weaver. Решил проблему - выкачал библиотеку, удалил секцию weaver из aop.xml и выложил измененную библиотеку к себе в артифактори. И подтянул в свой проект измененную библиотеку.

Минус данного способа в том, что как только появляется новая версия библиотеки - нужно будет ее выкачивать, изменять и выкладывать. Если подскажете более изящный способ разрешения данной проблемы, буду вам признателен! Если ничего в голову не приходит, то проблему можно закрывать.
