### ISSUE TITLE
Make it possible to set test ID so that Allure recognizes it in invocation history

### ISSUE THREAD

**Issue by kkarmakul** [kochetkov-ma/kotest-allure#6]
As a QA or software engineer I'd like to see a history of a test invocations over time in Allure. It is important to see when a test got broken and when it got back to OK.
As a QA engineer I'd like to set this ID in a rather simple way, say using an annotation like [@AllureId ](https://github.com/allure-framework/allure-java/blob/master/allure-java-commons/src/main/java/io/qameta/allure/AllureId.java) (from [allure-java-commons](https://mvnrepository.com/artifact/io.qameta.allure/allure-java-commons), since [2.10.0](https://github.com/allure-framework/allure-java/releases/tag/2.10.0)). Or, in a test name, like this (the preferred way):
```kotlin
  "Check /health endpoint".allureId("1024") { ...
```
or
```kotlin
  "Check /health endpoint" { 
      allureId = 1024
      ...
```
or
```kotlin
  "[1024] Check /health endpoint" { ...
```

kotlin: 1.7.10
kotest: 5.4.2
allure: 2.12.0

**Comment by kochetkov-ma** [comment]
Check this > https://github.com/kochetkov-ma/kotest-allure/releases/tag/v5.4.2
